### ISSUE TITLE
Option to convert subtitle format

### ISSUE THREAD

**Issue by oczkers** [QNapi/qnapi#10]
For example */txt -> srt

**Comment by zadziora** [comment]
This is good feature - thought I think TXT might be just renamed to SRT and it will be ok.

**Comment by krzemin** [comment]
Actually renaming is not a real conversion.

It would be nice to have general conversion mechanism (any format to any format including input auto-detection). But that require reliable way to retrieve FPS from any kind of movie file.

**Comment by zadziora** [comment]
You are absolutelly right.
My mistake.
I think SRT is a good format to have.

**Comment by krzemin** [comment]
I think I've found multi-platform way to retrieve meta-data from any kind of movie file.

https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1977

However it requries ffprobe which is part of ffmpeg package in most of Linux distros. In case of Windows/OSX there are static builds of ffprobe only (http://ffmpeg.zeranoe.com/builds/win32/static/ and https://evermeet.cx/ffmpeg/) which could be shipped with installer/dmg.

**Comment by krzemin** [comment]
General subtitle format conversion (from any format to any) is now implemented. There is support for 4 formats: SRT, mDVD, TMP, MPL2. Beside automatic conversion during subtitle post-processing, there is new conversion window where subtitles can be converted afterwards (including frame rate changing).

However nothing for free. Now **ffprobe** binary (from ffmpeg package) is required for frame rate detection. Static binaries will be provided with exe/zip/dmg packages for Windows/OSX which increase their size a bit. Under Linux ffmpeg should be declared as package dependency.
