### ISSUE TITLE
Utrata informacji o kolorze podczas konwertowania.

### ISSUE THREAD

**Issue by zylxpl** [QNapi/qnapi#100]
Podczas konwertowania napisów zostaje utracona informacja o kolorze formatowania, chociaż sam tag zostaje przekonwertowany. Przykładowo:
`{3415}{3515}{C:$ffff00}.:: Grupa Hatak - Hatak.pl ::.|przedstawia`
po konwersji na SubRip wygląda tak:
`35
00:02:16,600 --> 00:02:20,600
<font color="">.:: Grupa Hatak - Hatak.pl ::.
przedstawia`
A powinno być:
`<font color="#00ffff">.:: Grupa Hatak - Hatak.pl ::.
przedstawia`
Co ciekawe, informacja o kolorze zostaje wykasowana także, gdy plik źródłowy jest już w formacie na który chcemy napisy przekonwertować:
`{3415}{3515}{c:}.:: Grupa Hatak - Hatak.pl ::.|przedstawia`
Co stanowi większy problem, gdyż część odtwarzaczy stosuje w takim przypadku kolor czarny i napisy stają się nieczytelne.

**Comment by krzemin** [comment]
Naprawione. Dzięki za zgłoszenie problemu :)

**Comment by zylxpl** [comment]
Potwierdzam, że naprawione, ale ciągle nie działa do końca prawidłowo. Problem polega na tym, że w SRT format koloru to #rrggbb (red green blue), zaś w microDVD i MPL2 schemat jest odwrócony i wygląda $BBGGRR (blue green red). Podczas konwersji program po prostu przepisuje wartości kolorów zamiast zamienić ich kolejność w efekcie otrzymujemy zupełnie nowy kolor w formatowaniu.
