### ISSUE TITLE
Multi language subtitles download

### ISSUE THREAD

**Issue by zadziora** [QNapi/qnapi#11]
I quess it would be nice to download more than one subtitles language version.
For example if there are no subtitles yet for language A I have to change in options to dowload English subtitles.
So dear DEVS if you just can think to add the option to dowload subtitles in addtional language version if there are no subtitles in default language that would be great.

BTW:
Great job!!

**Comment by krzemin** [comment]
That would be really nice feature. And not so hard to implement.

**Comment by krzemin** [comment]
The feature is now implemented and will be available in 0.1.8 release.
