### ISSUE TITLE
QNapi hangs if launched without arguments

### ISSUE THREAD

**Issue by luigino** [QNapi/qnapi#118]
I must admit I hadn't actually tested it in depth until now, but after the first configuration run, nothing happens. No window opens, no error message, no obvious problem shown by gdb.
Downloading works normally if an argument is passed though.

This on openSUSE  Tumbleweed and Leap 42.3.

**Comment by krzemin** [comment]
Application should install itself into desktop tray. However you may encounter some problems (like #17), depending on your Qt version & desktop environment used.
Desired behavior on system tray being unsupported is to show an open dialog immediately, but few desktop environments report its availability wrongly.

**Comment by luigino** [comment]
Uh oh, my bad. Icon was there, but plasma5 puts them in a hidden menu by default.
