### ISSUE TITLE
cant download subs from napisy24.pl

### ISSUE THREAD

**Issue by spoksik** [QNapi/qnapi#12]
i cant  even login to napisy24.pl from qnapi  (win 8.1)

**Comment by krzemin** [comment]
Not investigated deeply, but I suppose that culprit is current method for determining subtitle file name in packed archive.

https://github.com/QNapi/qnapi/blob/master/src/qnapisy24engine.cpp#L415

**Comment by spoksik** [comment]
generally u cant download subs from napisy24.pl without account...

**Comment by krzemin** [comment]
Napisy24 engine doesn't require (and for now doesn't even allow) you to pass credentials, just use fixed ones.
