### ISSUE TITLE
Raspbian

### ISSUE THREAD

**Issue by RafalHo** [QNapi/qnapi#134]
Witam,

Czy jest szansa na wersję działającą na nowym Raspbianie?
W repozytorium jest tylko wersja 0.1.9.

Z góry dziękuję za info.
Pozdrawiam Raf

**Comment by AngryPenguinPL** [comment]
Próbowałeś tę paczkę? http://ppa.launchpad.net/krzemin/qnapi/ubuntu/pool/main/q/qnapi/qnapi_0.2.3-1_armhf.deb
Pochodzi z PPA dla Ubuntu, jak widzisz jest też build dla ARM. Osobiście nie testowałem, bo nie mam urządzeń tego ARM.

**Comment by krzemin** [comment]
Alternatywnie jest jeszcze obraz dockerowy: https://hub.docker.com/r/qnapi/qnapi-armhf

**Comment by RafalHo** [comment]
@AngryPenguinPL dzięki wielkie, zainstalowane i działa.

Problem mam tylko z ustawieniem alternatywnego języka na "none", ale z tego co widzę nie jestem jedyny.
Problem występuje zarówno na świeżo zainstalowanej kopii Raspbiana i Win 10.

**Comment by RafalHo** [comment]
Jeszcze jeżeli mogę liczyć na pomoc, czy podpowiecie jak z konsoli odpalić przeszukiwanie napisów w całym folderze i podfolderach?
Użyłem takiego polecenia, lecz wysypuje się na pierwszej pozycji, do której nie znajdzie napisów.
`qnapi -c -lb none /home/pi/seriale/*.*`

**Comment by krzemin** [comment]
Spróbuj:
```
for f in `ls /home/pi/seriale/*.*`; do qnapi -c -lb none $f; done
```

**Comment by RafalHo** [comment]
Dodałem /*/ żeby przeszukiwał wszystkie podkatalogi w danym folderze.
Problem pojawia się przez spacje w nazwach plików (dodałem echo, żeby sprawdzić)

> for f in `ls /home/pi/Brak_napisów/*/*.*`;
> do echo $f
> qnapi -c -lb none $f;
> done

Efekt szukania jednego pliku (Blindspot - 3x05.mkv):

/home/pi/Brak_napisów/_wspolne_/Blindspot
QNapi 0.2.3, http://qnapi.github.io
wersja Qt: 5.7.1

Nie znaleziono pliku!

 --
 QNapi

 0.2.3, http://qnapi.github.io
wersja Qt: 5.7.1

Nie znaleziono pliku!

3x05.mkv
QNapi 0.2.3, http://qnapi.github.io
wersja Qt: 5.7.1

Nie znaleziono pliku!

**Comment by RafalHo** [comment]
Problem rozwiązany, może trochę na około, ale działa.
Zastosowałem zmianę nazwy - wszystkie spacje zamieniane na --, później kod podany przez @krzemin  i po wszystkim powrót do nazw ze spacjami ;)
Wszystko załadowane do crona i pięknie działa szukając dwa razy dziennie napisów do seriali ;)

```
rename 's/ /--/g' /home/pi/seriale/*.*;

for f in ls /home/pi/seriale/*.*;
do qnapi -c -lb none $f;
done

rename 's/--/ /g' /home/pi/seriale/*.*;
```

Dzięki za pomoc :)

**Comment by krzemin** [comment]
Stawiałbym, że to powinno wystarczyć (`"$f"` zamiast `$f`):
```for f in `ls /home/pi/seriale/*.*`; do qnapi -c -lb none "$f"; done```

**Comment by RafalHo** [comment]
Niestety, na samym początku o tym pomyślałem, ale dalej traktuje wyniki jak wcześniej.
