### ISSUE TITLE
Add ability to scan given directory and download subtitles from CLI

### ISSUE THREAD

**Issue by Antoniossss** [QNapi/qnapi#140]
So right now I have to do 

`qnapi -c -d full/path/to/movie/with/extension.mp4 `
So I have to provide exact filename. It would be nice, that if I provide only a directory, qnapi will scan directory and download subtitles for found content like this

`qnapi -c -d full/path/to/movie/with/`

This is handy in case of automated scripts. I would like subtitles to download automaticly after torrent is fully downloaded. For scritping purposes I have only output directory as input paramenter, not exact filename. Besides, single torent can have multiple files inside, and for every one of them I would like to trigger subs download. Thats why scan would be very helpfull.

**Comment by RafalHo** [comment]
```
for movie in `ls /full/path/to/movie/with/*/*.*`;
do qnapi -c $movie 
done
```

**Comment by Antoniossss** [comment]
Can be done via CLI, on widnows as well. But that a feature request for noobs ;]
