### ISSUE TITLE
Problem z kompilacją qnapi 0.1.8

### ISSUE THREAD

**Issue by gienekpa** [QNapi/qnapi#16]
Mój   system operacyjny to Linux Open Suse 13.2 64bit
Pobrałem qnapi

> git clone --recursive https://github.com/QNapi/qnapi.git

Doinstalowałem masę brakujących bibliotek i wydałem polecenie

> /usr/lib64/qt5/bin/qmake

potem przeprowadziłem kompilację

> gienek@linux-ygzy:~/Pulpit/qnapi-0.1.8> make
> uic ui/frmprogress.ui
> uic ui/frmlistsubtitles.ui
> uic ui/frmsummary.ui
> uic ui/frmscan.ui
> uic ui/frmoptions.ui
> uic ui/frmabout.ui
> uic ui/napiprojekt/frmnapiprojektconfig.ui
> uic ui/frmupload.ui
> uic ui/frmcorrect.ui
> uic ui/frmreport.ui
> uic ui/opensubtitles/frmopensubtitlesconfig.ui
> compiling src/main.cpp
> compiling src/forms/frmprogress.cpp
> compiling src/forms/frmlistsubtitles.cpp
> compiling src/forms/frmsummary.cpp
> compiling src/forms/frmscan.cpp
> compiling src/forms/frmoptions.cpp
> compiling src/forms/frmabout.cpp
> compiling src/forms/frmnapiprojektconfig.cpp
> compiling src/forms/frmupload.cpp
> compiling src/forms/frmcorrect.cpp
> compiling src/forms/frmreport.cpp
> compiling src/forms/frmopensubtitlesconfig.cpp
> compiling src/qcumber/qmanagedrequest.cpp
> compiling src/qcumber/qmanagedsocket.cpp
> compiling src/qcumber/qsingleapplication.cpp
> compiling src/qnapiconfig.cpp
> compiling src/qnapiapp.cpp
> compiling src/qnapicli.cpp
> compiling src/qnapi.cpp
> compiling src/qnapiabstractengine.cpp
> compiling src/qnapiprojektengine.cpp
> compiling src/qopensubtitlesengine.cpp
> compiling src/qmultiparthttprequest.cpp
> compiling src/movieinfo.cpp
> compiling src/qnapiopendialog.cpp
> compiling src/qnapilanguage.cpp
> compiling src/qnapisy24engine.cpp
> compiling src/synchttp.cpp
> compiling src/syncxmlrpc.cpp
> compiling src/encodingutils.cpp
> compiling deps/libmaia/maiaObject.cpp
> compiling deps/libmaia/maiaFault.cpp
> compiling deps/libmaia/maiaXmlRpcClient.cpp
> compiling deps/libmaia/maiaXmlRpcServer.cpp
> compiling deps/libmaia/maiaXmlRpcServerConnection.cpp
> compiling src/qcumber/qinterprocesschannel.cpp
> rcc res/resources.qrc
> compiling tmp/qrc_resources.cpp
> moc src/forms/frmprogress.h
> compiling tmp/moc_frmprogress.cpp
> moc src/forms/frmlistsubtitles.h
> compiling tmp/moc_frmlistsubtitles.cpp
> moc src/forms/frmsummary.h
> compiling tmp/moc_frmsummary.cpp
> moc src/forms/frmscan.h
> compiling tmp/moc_frmscan.cpp
> moc src/forms/frmoptions.h
> compiling tmp/moc_frmoptions.cpp
> moc src/forms/frmabout.h
> compiling tmp/moc_frmabout.cpp
> moc src/forms/frmnapiprojektconfig.h
> compiling tmp/moc_frmnapiprojektconfig.cpp
> moc src/forms/frmupload.h
> compiling tmp/moc_frmupload.cpp
> moc src/forms/frmcorrect.h
> compiling tmp/moc_frmcorrect.cpp
> moc src/forms/frmreport.h
> compiling tmp/moc_frmreport.cpp
> moc src/forms/frmopensubtitlesconfig.h
> compiling tmp/moc_frmopensubtitlesconfig.cpp
> moc src/qcumber/qmanagedsocket.h
> compiling tmp/moc_qmanagedsocket.cpp
> moc src/qcumber/qsingleapplication.h
> compiling tmp/moc_qsingleapplication.cpp
> moc src/qnapiapp.h
> compiling tmp/moc_qnapiapp.cpp
> moc src/qnapiopendialog.h
> compiling tmp/moc_qnapiopendialog.cpp
> moc src/qnapilanguage.h
> compiling tmp/moc_qnapilanguage.cpp
> moc src/qnapithread.h
> compiling tmp/moc_qnapithread.cpp
> moc src/synchttp.h
> compiling tmp/moc_synchttp.cpp
> moc src/syncxmlrpc.h
> compiling tmp/moc_syncxmlrpc.cpp
> moc deps/libmaia/maiaObject.h
> compiling tmp/moc_maiaObject.cpp
> moc deps/libmaia/maiaFault.h
> compiling tmp/moc_maiaFault.cpp
> moc deps/libmaia/maiaXmlRpcClient.h
> compiling tmp/moc_maiaXmlRpcClient.cpp
> moc deps/libmaia/maiaXmlRpcServer.h
> compiling tmp/moc_maiaXmlRpcServer.cpp
> moc deps/libmaia/maiaXmlRpcServerConnection.h
> compiling tmp/moc_maiaXmlRpcServerConnection.cpp
> moc src/qcumber/qinterprocesschannel.h
> compiling tmp/moc_qinterprocesschannel.cpp
> linking qnapi
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot open output file qnapi: Jest katalogiem
> collect2: error: ld returned 1 exit status
> Makefile:336: polecenia dla obiektu 'qnapi' nie powiodły się
> make: *** [qnapi] Błąd 1
> gienek@linux-ygzy:~/Pulpit/qnapi-0.1.8>

Szczerze powiedziawszy to ugrzązłem i za bardzo nie wiem jak ruszyć dalej. Czy mógłbyś pomóc mi rozwiązać problem z kompilacją?

Szukam też nieskutecznie wersji Qunapi 0.1.6 rc korzystałem z niej przez wiele lat i kompilowała się u mnie na kolejnych wersjach OpenSuse bez najmniejszego problemu. Niestety w internecie jej już nie znalazłem. Jeśli nie uda mi się zainstalować Qnapi 0.1.8 to może podpowiedziałbyś mi skąd mogę pobrać wersję 0.1.6?

**Comment by krzemin** [comment]
```
...
linking qnapi
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot open output file qnapi: Jest katalogiem
```

Wygląda na to, jakby linker chciał zapisać binarkę, ale katalog o nazwie `qnapi` już był obecny, wobec czego ten błąd.

Spróbuj `make distclean` a potem jeszcze raz `qmake` i `make`, i zobacz czy pomogło.

**Comment by gienekpa** [comment]
Usunąłem katalog ze źródłami a potem pobrałem go ponownie

następnie 

> /usr/lib64/qt5/bin/qmake
potem 

> make

i teraz wywaliło mi błąd

compiling tmp/moc_maiaXmlRpcServerConnection.cpp
moc src/qcumber/qinterprocesschannel.h
compiling tmp/moc_qinterprocesschannel.cpp
> linking qnapi
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libGL.so when searching for -lGL
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lGL
> collect2: error: ld returned 1 exit status
> Makefile:336: polecenia dla obiektu 'qnapi' nie powiodły się
> make: *** [qnapi] Błąd 1
> gienek@linux-ygzy:~/Pulpit/qnapi>

Nie wiem czemu wywaliło mi  

> cannot find -lGL

skoro mam

> gienek@linux-ygzy:~/Pulpit/qnapi> rpm -qa | grep Mesa-libGL-devel
> Mesa-libGL-devel-10.3.7-91.6.1.x86_64
> gienek@linux-ygzy:~/Pulpit/qnapi>

> gienek@linux-ygzy:~/Pulpit/qnapi> rpm -qa | grep libqt5-qtbase-devel
> libqt5-qtbase-devel-5.4.2-206.1.x86_64
> gienek@linux-ygzy:~/Pulpit/qnapi>

Chyba, że to nie o pliki należące do pakietu Mesa-libGL-devel chodzi kompilatorowi?

**Comment by krzemin** [comment]
Sprawdź ten wątek: http://stackoverflow.com/questions/17552136/skipping-incompatible-libgl-so

**Comment by Fisiu** [comment]
Nie wiem czy problem rozwiązany, ale [pakiety](https://software.opensuse.org/download/package?project=home:Fisiu&package=qnapi) dla openSUSE są dostępne póki co w moim repozytorium. Niedługo pakiet trafi do głównego repozytorium ;-)
