### ISSUE TITLE
qnapi icon appears in wrong place if unity desktop environment (ubuntu) is used

### ISSUE THREAD

**Issue by MikolajQ** [QNapi/qnapi#17]
Qnapi icon appears on the left edge of the unity panel and covers the name of currently opened window. It should rather appear next to the other indicators (on the right side of the unity panel). I use Ubuntu 14.04 LTS. Besides that, qnapi works as expected. Thnks.

**Comment by krzemin** [comment]
Basically, you have 2 options:

* make sure you compile qnapi against Qt 5.5+; only starting from this release, Qt supports unity's libindicator, which means that qnapi's icon is placed in right place, near other indicators

* use one of workaround to bring back tray icon for qnapi: http://askubuntu.com/questions/151112/how-do-i-get-the-skype-status-icon-back-on-panel-tray

**Comment by MikolajQ** [comment]
Is there any chance You will provide ppa with working packages? Compiling against qt5.5 (from some ppa) produces not working binary (./qnapi
./qnapi: symbol lookup error: ./qnapi: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject). sni-qt didn't help. gsettings set com.canonical.Unity.Panel systray-whitelist "['all']" - doesn't work any more with 14.04. I'm sorry but it is too difficult for an ordinary user to get qnapi 0.1.8 work under Ubuntu 14.04 LTS. ppa will make this application reachable.

**Comment by krzemin** [comment]
I didn't have any problems compiling qnapi on 14.04 LTS using Qt5 grabbed here: http://www.qt.io/download-open-source/
`/path/to/installed/qmake && make` and I had working binary

It would be great if official qnapi debian packages were updated: https://packages.debian.org/search?keywords=qnapi
I wrote to original debian maintainer (prezu), but with no response yet.

I will not provide PPA. But, as a temporary solution, I could provide pre-built static binaries (similar as for Windows and OSX).

Other way to solve this problem in a desktop-independent way could be #18

**Comment by krzemin** [comment]
https://github.com/QNapi/qnapi/blob/master/.travis.yml

This file contains step-by-step compilation guide for Ubuntu.

**Comment by miniworm** [comment]
Could you provide pre-built static binaries (or deb packages) for latest qnapi? It's really great that new versions are developed but lack of binaries for Linux is really sad.

**Comment by miniworm** [comment]
Maybe it's good idea to take over debian package maintenance? I'me affraid that prezu will not respond after so many years and closing of his original website.

**Comment by krzemin** [comment]
QNapi 0.1.9 was actually packaged by Prezu soon after it has been released.
https://packages.debian.org/pl/sid/qnapi

I'm not sure if it's available for Ubuntu users as well.

Anyway, it's good idea to provide static binaries. I'll try to do that soon (#26).

**Comment by miniworm** [comment]
This Debian package is usable in Ubuntu, but only in latest version (15.04) with manual install (no 0.1.9 in Ubuntu repositories). Sadly not on 14.04 LTS (dependencies - too old qt5 libraries in 14.04).

Probably it will change for good, but IMHO in 2016. Now merging window for Debian-->Ubuntu migration closed for Ubuntu 15.10 so it will be imported to Ubuntu in next merging window (early 2016, preparation to Ubuntu 16.04 LTS).

**Comment by Recydywa** [comment]
Qnapi was updated today in 15.10 to 0.1.9.

I reported bug yesterday and today they synced package from Debian so that was a very fast reaction.

**Comment by miniworm** [comment]
Nevermind (at least for me) - i've compiled package for Ubuntu 14.04 LTS so it's enough for me for now.
