### ISSUE TITLE
qnapi - ubuntu/linux - config file

### ISSUE THREAD

**Issue by krypton9208** [QNapi/qnapi#176]
I'm trying to write script for ubuntu server (without gui) - to download subs but, i can't find file with settings (i found into my macos and i want justy past it to server).

----Update (29.10.2020)
File wasn't created, but if you create file - qnapi will read it.
~/.config/qnapi.ini

Ready do close ;)

**Comment by krystaDev** [comment]
Update.
File wasn't created, but if you create file - qnapi will read it.
`~/.config/qnapi.ini `

Ready do close ;)
