### ISSUE TITLE
napisy24 not working sometimes

### ISSUE THREAD

**Issue by oczkers** [QNapi/qnapi#23]
qnapi reports succesful download but shortcut to napisy24.pl is created instead

![snapshot](https://photos-5.dropbox.com/t/2/AAAoKXyLovoIEpkSox1ADQS0akNCa4KF6SI3mv89rpRu5Q/12/21348707/png/32x32/1/1441270800/0/2/Untitled.png/COOClwogASACIAMgBCAFIAYgBygBKAc/7xSb1_OGWZ57gbdrhf4GIIe-epSgaXG8BqpO43Gyd5k?size=1600x1200&size_mode=2)

**Comment by krzemin** [comment]
Is this problem reproducible for certain movie files? Or is it totally random?
Could you provide link to a file which such behaviour concern?

What with native Napisy24 application, does it create shortcut too?

Anyway, most likely this is problem with Napisy24 API, which you should report here: http://forum.napisy24.pl/viewforum.php?f=9

**Comment by oczkers** [comment]
Fixed snapshot:
![fixed snapshot](http://s14.postimg.org/3nye4ype9/7x_Sb1_OGWZ57gbdrhf4_GIIe_ep_Sga_XG8_Bqp_O43_Gyd5k.png)

I've seen this problem before few times (only for specified files) but looks like it's fixed now. I'll test napisy24 app and report as soon as i reproduce.

**Comment by krzemin** [comment]
I can confirm that this is QNapi issue.

There are several files in archive provided by Napisy24 service, but QNapi expects only one. In this case, it extracts wrong file which is not subtitles file, but url shortcut.

Thanks for reporting :) I will fix it soon.
