### ISSUE TITLE
[Prośba] Dodajcie angielskie napisy z SubScene

### ISSUE THREAD

**Issue by debofsky** [QNapi/qnapi#25]
Proszę, abyście dodali możliwość automatycznego pobierania napisów w języku angielskim ze strony SubScene.

Pozdrawiam.

**Comment by krzemin** [comment]
Czy SubScene udostępnia jakieś API? Jedyne, co znalazłem, to dość leciwy wątek, z którego niewiele wynika: http://v2.subscene.com/forums/t/43717.aspx

Bez dedykowanego, prostego w użyciu API, zostaje scrapping HTML, ale tego raczej nie chciałbym implementować w QNapi (problemy z utrzymaniem, HTML może się w każdej chwili zmienić i silnik pobierania przestanie działać). Chyba, że ktoś napisze działającego gotowca, to mogę zaakceptować PR.

**Comment by Recydywa** [comment]
Nie wiem czy SubScene ma jakieś API ale wiem o istnieniu takiego programu który działa na Linuksie i pobiera napisy z tej strony.

 https://github.com/iamsudip/pysub-dl

http://www.iamsudip.xyz/pysub-dl/

Ale wygląda na to że ten program jest scrapperem: Movie subtitle downloader - subscene.com scrapper
