### ISSUE TITLE
Provide statically compiled Linux package

### ISSUE THREAD

**Issue by krzemin** [QNapi/qnapi#26]

**Comment by miniworm** [comment]
BUMP - right now it's even more important when modern Qt is needed.

**Comment by arjamizo** [comment]
Can I request for comments on this issue? Is this going to be provided?

**Comment by krzemin** [comment]
Well, hard to say. I don't have so much time and this task is rather time consuming.

When you want to compile a Qt application as a static binary, it's required to separately compile a whole Qt that gives you static Qt libraries. After that I tried to compile QNapi in static mode, but still some libraries were loaded dynamically (I don't know why). Apart from the fact, application was ugly because fonts/colors were picked randomly.

However, I haven't tried with Qt 5.6 yet.

**Comment by arjamizo** [comment]
Why does this app require QT? only for GUI or it is also used in its core functionality?

**Comment by krzemin** [comment]
@arjamizo Both GUI and core.

As now there is up to date PPA (#63), static package is probably not necessary so much. Anyway it was proposed as temporary solution in #17.

**Comment by arjamizo** [comment]
@krzemin so... maybe its better to write extremely simple GUI in GTK, hmm?

**Comment by krzemin** [comment]
@arjamizo But why?
