### ISSUE TITLE
Make app retina display ready

### ISSUE THREAD

**Issue by krzemin** [QNapi/qnapi#27]
As one of users twitted:
https://twitter.com/ChojnackiDawid/status/645257863158460417
https://twitter.com/ChojnackiDawid/status/646158413253222400

**Comment by remik** [comment]
Did you test it on retina? It still looks the same.

**Comment by krzemin** [comment]
I used HiDPI emulation mode in Mavericks and there was noticeable difference.
But concluding that tweet (https://twitter.com/ChojnackiDawid/status/668522969115815936) it seems to be working. Are you sure that you have latest 0.2.0 version?

**Comment by remik** [comment]
Strange.
I cleaned app and settings via AppCleaner, installed 0.2.0 - I got new icons but still not-retina and fonts were horrible, check about and there was 0.2.0 info. 
I just installed Qt 5.X headers to check if I can help and I see retina icons and fonts are clean.
I am afraid to remove headers now :P

**Comment by hyperionide** [comment]
I have the same problem. I cleaned the old version of QNapi with AppCleaner, installed 0.2.1 and only the desktop/launchpad icon is clear; status bar icon, fonts and the app itself are pixelized. I'm running El Capitan 10.11.2
