### ISSUE TITLE
OS X 10.11 menubar icon

### ISSUE THREAD

**Issue by darekpoznan** [QNapi/qnapi#30]
Po aktywacji opcji autoukrywania paska menu ikona Qnapi nie jest widoczna - w jej miejscu widoczna jest pusta przestrzeń, po której kliknięciu dostępne jest standardowe menu podręczne.
Ta pusta przestrzeń pojawia się czasami miedzy widocznymi już ikonami lub też jako pierwsza od lewej (przed innymi ikonami w pasku menu).

**Comment by krzemin** [comment]
1. Sprawdź proszę czy problem nadal występuje w wersji 0.2.0.
2. Jeśli tak, poproszę o screenshot.

**Comment by darekpoznan** [comment]
Witam,

problem nadal występuje w wersji 0.2.0 - ikona qnapi jest niewidoczna, ale klikając przed pierwszą ikoną jest możliwość wywołania funkcji qnapi
automatyczne ukrywanie paska menu włączone: http://cl.ly/image/0s0B2S2W1W1u
automatyczne ukrywanie paska menu wyłączone: http://cl.ly/image/1e3h0f0A3h05

— 
Pozdrawiam,
Darek
admpoznan@gmail.com
Sent with Airmail

Od: Piotr Krzemiński <notifications@github.com>
Odpowiedz: QNapi/qnapi <reply@reply.github.com>
Data: 2015.11.24 at 18:04:11
Do: QNapi/qnapi <qnapi@noreply.github.com>
DW: darekpoznan <admpoznan@gmail.com>
Temat:  Re: [qnapi] OS X 10.11 menubar icon (#30)  

Sprawdź proszę czy problem nadal występuje w wersji 0.2.0.
Jeśli tak, poproszę o screenshot.

**Comment by krzemin** [comment]
Wygląda na to, że problem dotyczy Qt, a nie samego QNapi. 

Bug został zgłoszony w Qt, pozostaje czekać na rozwiązanie.
https://bugreports.qt.io/browse/QTBUG-48960

Taki sam problem w innej aplikacji używającej Qt: https://github.com/owncloud/client/issues/3918

**Comment by krzemin** [comment]
Ticket w bugtrackerze Qt zamkniety, pozostaje czekac na wydanie Qt 5.6.
https://bugreports.qt.io/browse/QTBUG-48960
