### ISSUE TITLE
Broken encoding after converting SRT file from UTF-8 BOM to UTF-8 

### ISSUE THREAD

**Issue by tapcio** [QNapi/qnapi#34]
Broken encoding after converting SRT file from UTF-8 BOM to UTF-8 
Disabling convert option downloads original SRT file and it is in UTF-8 BOM already.

Files here:
http://www26.zippyshare.com/v/i659vTVq/file.html
input.srt is downloaded with covert off, output is downloaded with conversion.

Tested platform: Windows 10.
Tested versions: official 0.1.9, current git master (b2ab353a99534fb38145bbd4994dd201a0cf17b9) build with Qt 5.5.1 mingw492_32

**Comment by krzemin** [comment]
Thanks for the reporting.
In fact, file encoding detection was broken. Could you confirm that problem no longer exists on current master?

**Comment by tapcio** [comment]
Thanks, it's fixed.
