### ISSUE TITLE
Zapasowy język napisów nie działa pod OS X

### ISSUE THREAD

**Issue by JakubAnderwald** [QNapi/qnapi#36]
Ustawiłem podstawowy język napisów polski, a zapasowy - angielski. Przy użyciu opcji "pobierz napisy" program nie znajduje żadnych napisów.

Po przestawieniu podstawowego języka na angielski, program znajduje 4 pliki z napisami dla tego samego odcinka serialu. Wydaje się, że powinna to rozwiązać opcja "zapasowy język napisów" i program po niemożliwości ściągnięcia polskiej wersji, ściągnąłby angielską - ale tak się nie dzieje.

**Comment by krzemin** [comment]
Problem naprawiony. Dzięki za zgłoszenie błędu.

**Comment by JakubAnderwald** [comment]
Czy jest już wersja skompilowana pod MacOS do ściągnięcia z tą poprawką? Czy muszę poczekać?

**Comment by krzemin** [comment]
Poprawka będzie obecna w wersji 0.2.0.

**Comment by bentkowski** [comment]
W ubuntu 18.04 również nie można ustawić i zapisać w opcjach alternatywnego języka dla napisów.
