### ISSUE TITLE
Convertion options for file format work after deselectin whole converter (Linux, 0.1.9, x64)

### ISSUE THREAD

**Issue by miniworm** [QNapi/qnapi#38]
I've selected to convert subtitles to SRT format. Then I've disabled converter so everything on converter tab is grayed-out and disabled. In this case charset conversion is really disabled but format conversion still works - final files are in SRt format regardless of original format.

**Comment by krzemin** [comment]
Well, I can partially confirm this bug. Actual **format conversion** doesn't take place, but **file extension** is changed according to grayed-out option, but shouldn't.

**Comment by miniworm** [comment]
So it's even worst - extension changes with wrong format inside.

IMHO there should be 2 independent switches - on/off for charset conversion and on/off for format conversion.

**Comment by krzemin** [comment]
I fixed it by not touching the extension when post-processing is not enabled.

In fact, there are independent switches for encoding/format/extension conversion, but they are controlled by "global" post-processing switch.
