### ISSUE TITLE
getting subtitles for MKV files (Linux, 0.1.9, x64)

### ISSUE THREAD

**Issue by miniworm** [QNapi/qnapi#39]
qnapi doesn't find any subtitles for MKV files but for sure they are available for this movie on websites.

**Comment by krzemin** [comment]
QNapi doesn't perform heuristic search based on filename. If concrete file hash wasn't added to specific database, QNapi simply won't find it.

**Comment by miniworm** [comment]
Ok, it's clear. There in no other search option available (based on title and time etc.)?
