### ISSUE TITLE
File conversion from menu doesn't work (Linux, x64, 0.2.1)

### ISSUE THREAD

**Issue by miniworm** [QNapi/qnapi#43]
File conversion from menu doesn't work - when i select TXT file and want it to be converted to SRT. FPS checking works but then no conversion takes place. I've attached example subtitle file which i wan to convert, but it doesn't work for all files i've tried.
[127 godzin.txt](https://github.com/QNapi/qnapi/files/46567/127.godzin.txt)

**Comment by krzemin** [comment]
Caused by the same reason as #41
