### ISSUE TITLE
Opcja wyboru języka

### ISSUE THREAD

**Issue by yogurd** [QNapi/qnapi#45]
Czy jest możliwe dodanie opcji, żeby w oknie wyboru napisów do ściągnięcia wyświetlały się napisy i w języku podstawowym i zapasowym ? 

Chodzi o to, że czasami człowiek musi popróbować różnych napisów, żeby trafić w te które pasują. Czasami (bardzo sporadycznie), żadne z podstawowych napisów nie są satysfakcjonujące. Wtedy trzeba wejść do opcji i zamienić ze sobą języki. A taka opcja rozwiązywała by ten problem.

**Comment by krzemin** [comment]
Bardzo dobra propozycja.

**Comment by Tirith2708** [comment]
Czy nie lepiej było by dodać możliwość włączenia w opcjach dodatkowego pola w menu kontekstowym - "Pobierz napisy w języku zapasowym" ?

**Comment by yogurd** [comment]
To też by było fajne. Ale kurde, ja osobiście mam tak nababrane w menu kontekstowym, że aż strach. Nie wiem jak problematycznym byłoby wprowadzenie jednej i drugiej opcji. 
Można by też dodać opcję, pobierz wszystkie znalezione/pobierz zaznaczone.

**Comment by Tirith2708** [comment]
No właśnie ja mam w menu kontekstowym pustkę (dzięki w10 manager'owi) a zawsze ściągam napisy w 2 językach (ang. dla mnie a polskie dla rodziny). Zgadzam się że najlepiej było by wprowadzić obie opcje, ale to już zależy od @krzemin

**Comment by yogurd** [comment]
@Tirith2708 w10 manager ? to w10 ma jakiś domyślny trick to porządkowania kontekstowego ? Coś więcej możesz napisać ?

**Comment by Tirith2708** [comment]
@yogurd Nie ma, ale możesz ściągnąć taki programik :) Spróbuj stąd - http://www.majorgeeks.com/files/details/windows_10_manager.html

**Comment by andrewpros** [comment]
Proponuję zostawić jedno menu kontekstowe, a to co ma robić dokładnie to już można skonfigurować w programie, kiedyś męczyłem o to twórcę napiprojekt, nawet zaakceptował propozycję, ale i tak ze 3 lata nic nie zrobił.

Problem który pojawia się czasami lub bardzo sporadycznie nie powinien rzutować na wszystkich użytkownikach i wprowadzać zmian wszystkim, gdzie problem pojawi się w 0.1% przypadków, a wprowadzenie takiej opcji albo mocno wpłynie na wszystkich albo będzie mniej wygodne dla samych zainteresowanych.

Najlepszym i najwygodniejszym sposobem, aby taką sporadyczną potrzebę wypełnić jest dodanie takiej funkcjonalności do okna podsumowującego, tak aby to było całkowicie opcjonalne.

I tak osoba z takim problemem musi odpalić materiał, aby stwierdzić czy pasuje.

Myślę, że można by dodać przycisk  "Nie wyłączaj okna po wyborze napisu" i po kliknięciu okno wchodziłoby w taki tryb "prób i błędów" dla tych którzy tego potrzebują, po wybraniu opcji program od nowa by wyszukał wszystkie napisy w obu wersjach językowych, wystarczyłoby klikać po napisach i program by je ściągał i zastępował (już dostępna opcja) ale nie zamykał by okna tak jak jest teraz.

Po ściągnięciu napisu można wtedy odpalić materiał i sprawdzić czy pasuje, jak nie to wygodnie wracamy do okna i wybieramy następne napisy, jak pasują to zamykamy Xem i tyle.

No coś w ten deseń, ale według nie najlepsza opcja. W innym wypadku tak jak teraz program działa trzeba by dodać albo opcje dla tych co chcą takie okno albo zmienić działanie wszystkim. Program pobiera teraz po kolei, a musiałby pobierać wszystko bez względu czy musi, to jest duża zmiana.

Oba rozwiązania są złe

- opcja dla tych co chcą, ale czy chcą cały czas, no właśnie raczej nie, bo dla sporadycznego problemu nikt nie chce przedłużać sobie ściągania "na wszelki wypadek", a już przy 3 materiałach to nie idzie za szybko, komu się chce wchodzić ciągle w opcje i przełączać
- wprowadzamy zmiany wszystkim, no i teraz wszystkim ściąga nie po kolei napisy, a naraz wszystkie wersje "na wszelki wypadek" według mnie odpada

Nie wspominając o tym, że utrzymywanie różnych interfejsów i innego działania tych samych funkcji obciąża twórcę programu.

Technicznie można by dodać kolejne menu dla tych co chcą, ale tak jak pisałem czy dla 0.1% przypadków warto? Ergonomiczne rozwiązania są lepsze, od razu scalają się z istniejącym interfejsem i są w pełni opcjonalne, nie trzeba przełączać co chwilę opcji, ani wmuszać wszystkim zmian, ergo nie przedłuża obecnego procesu dla sporadycznych przypadków, jednocześnie to co opisałem używało by się prosto i wygodnie.

Jak sądzicie?

**Comment by krzemin** [comment]
W przypadku dodatkowej pozycji w menu kontekstowym menedżera plików, to działałoby to na razie tylko na Windows. Makowcy mają  uproszczoną pozycję *Open with... -> QNapi* w menu kontekstowym, a linuksowcy albo sobie sami skonfigurują, albo w ogóle menu kontekstowego nie mają. Nie chciałbym pod tym względem dzielić użytkowników i jeśli już - lepiej byłoby zrobić jedno rozwiązanie, które działa na wszystkich platformach.

Docelowo najlepiej byłoby pewnie przemodelować UI flow pobierania napisów, być może umożliwiając tryb prób i błędów przez pozostawienie okna wyboru, być może uwzględniając też propozycję #48, jednak przy obecnym stanie kodu i pracochłonności takich większych zmian - to raczej nie jest propozycja na teraz (może w przyszłości, bliżej nieokreślonej).

Biorąc pod uwagę realia, najoptymalniej będzie dodać trzecią opcję do *Wyszukiwanie napisów* w ustawieniach - *Wyszukaj wszystkie napisy, także w języku zapasowym (najwolniej)*. Działałoby to zgodnie z początkową propozycją @yogurd. Zwiększyłoby to czas wyszukiwania, ale byłaby to przełączalna opcja, a nie domyślne zachowanie.

**Comment by andrewpros** [comment]
No właśnie takiej przełączanej opcji też warto by było uniknąć, bo wtedy za każdym razem gdyby ktoś chciał dopasować musiałby to zmienić i od nowa albo jechać cały czas z tą opcją co by mu zwalniało wyszukiwanie i dodatkowo obciążało serwisy, gdy nie byłoby to koniecznie potrzebne.

Ale skoro sprawa rozwojowa, może zrobię jakiś branch i podłubię.

**Comment by krzemin** [comment]
Opcja wyszukiwania napisów w obydwu językach zmerge'owana, pojawi się w wersji 0.2.1.
