### ISSUE TITLE
Nie pobiera napisów zapasowych

### ISSUE THREAD

**Issue by andrewpros** [QNapi/qnapi#46]
Jeżeli mamy ustawione w programie napisy zapasowe i ustawioną opcję przerwania wyszukiwania po znalezieniu pasujących napisów to w przypadku braku napisów PL i zapasowych nie sprawdza już napisów zapasowych w innych serwisach. Nie sprawdza też PL w innych.

Nie wiem jaki jest algorytm w źródle, a okienko szybko znika, ale wygląda na to, że przy tej konfiguracji nie sprawdza w ogóle innych serwisów.

Algorytm jest

- sprawdź serwis nr 1 PL, jak nie ma to zapasowy język serwis nr 1, jak nie ma to nara

A powinien być

- sprawdź serwis nr 1 PL, jak nie ma to nr 2 PL, jak nie ma to nr 3 PL, jak nie ma to wraca i od nowa, ale zapasowy np. EN

No przynajmniej mi się tak zdaje.

**Comment by krzemin** [comment]
Powinno być dokładnie tak, jak piszesz. Ale przez głupi błąd nie było. Naprawione :) dzięki za raport.
