### ISSUE TITLE
Język pobranych napisów w oknie podsumowania

### ISSUE THREAD

**Issue by andrewpros** [QNapi/qnapi#51]
Jakiś czas temu dodałem sobie takie coś do źródełek, w podsumowaniu pobranych napisów mam po ikonie język pobranych napisów w formacie [xx] gdzie xx to PL lub w moim przypadku EN, zależy co było.

Nie mogę z tego zrobić PR, a i nie wiem czy to tak powinno być rozwiązane, ale zgłaszam to jako propozycję.

Ja zmieniłem listę gotList w frmprogress na listę QPair => QString,QString

Co wymagało też zmiany w frmSummary::setSummaryList

Para ta przekazuje to co wcześniej czyli link do pliku oraz symbol języka pl lub np. en.

Jako, że program dwustopniowo sprawdza napisy, najpierw podstawowe potem dodatkowe dodałem sobie zmienną foundBackup by wiedzieć, że znalezione napisy są w języku zapasowym.

Tak potem dodaje do listy  gotList.append(qMakePair(queue[i], foundBackup ? languageBackup : language));

A w setSummaryList musiałem zrobić tak

QPair<QString, QString> successItem;
    foreach(successItem, listSuccess)
    {
QListWidgetItem* wi = new QListWidgetItem(succIcon,"[" + successItem.second.toUpper() + "] " + QFileInfo(successItem.first).fileName());
ui.lwSummary->addItem(wi);
    }

Tak tylko podaję jak ja to ogarnąłem, może się przyda. Pisałem pod kątem sytuacji wyboru języka dodatkowego, bo jak ktoś ściąga tylko PL to mu się ta opcja zbytnio nie przyda.

**Comment by krzemin** [comment]
Tak, pamiętam. Dlaczego nie możesz zrobić PR? Własny fork/branch i znacznie łatwiej byłoby uchwycić o co chodzi.

**Comment by andrewpros** [comment]
Bo zrobiłem to właśnie na branchu z mastera, nie z forka, po za tym nie chcę wchodzić z butami w sposób zrobienia, bo może masz lepszy. Do tego zmieniłem pliki projektu, bo release był na sztywno, no i debug działał.

To może zrobię forka i przykleję pliki, najwyżej skopiujesz/zmienisz z PR zamiast zatwierdzać.

**Comment by andrewpros** [comment]
Dobra jednak mi się udało https://github.com/QNapi/qnapi/pull/53 (chaba)

**Comment by krzemin** [comment]
Dalsza dyskusja w PR #53
