### ISSUE TITLE
[OS X] Wsparcie dla wyświetlaczy Retina

### ISSUE THREAD

**Issue by damiandziaduch** [QNapi/qnapi#52]
Cześć.

Czy będzie dodane wsparcie dla wyświetlaczy Retina? Aktualnie program wyświetla trochę "pikselozę" - nie ostre są okienka programów :)

Dowody w postaci zrzutów ekranów:
![zrzut 1](http://i1372.photobucket.com/albums/ag347/ddziaduch/Zrzut%20ekranu%202016-01-23%20o%2012.17.15_zpss94n351w.png)
![zrzut 2](http://i1372.photobucket.com/albums/ag347/ddziaduch/Zrzut%20ekranu%202016-01-23%20o%2012.16.50_zps93zcvgwt.png)
Pozdrawiam twórców :)

**Comment by krzemin** [comment]
Cóż, wsparcie dla retiny oficjalnie pojawiło się w wersji 0.2.0 (#27). U mnie działa, ale kilka osób zgłaszało "rozmycie" podobnie jak tutaj. Szczerze - nie wiem czym to jest spowodowane.

**Comment by damiandziaduch** [comment]
Czy instalacja QT z brew może pomóc?

**Comment by krzemin** [comment]
Nie wiem, możesz spróbować. Ja mam Qt zainstalowane przez instalator online stąd: http://download.qt.io/official_releases/online_installers/qt-unified-mac-x64-online.dmg

**Comment by damiandziaduch** [comment]
Zainstalowałem najnowsze Qt z brew i jest OK :+1:
