### ISSUE TITLE
QNapi Windows installer doesn't stop the running exec, thus runs into problems

### ISSUE THREAD

**Issue by karololszak** [QNapi/qnapi#55]
I had QNapi 0.2.0 running and when I launched 0.2.1 installer it showed an alert saying that it cannot write certain files because they are already in use. I closed the running qnapi myself and then it went on smoothly. I guess the installer should've closed the qnapi itself.

[Screenshot of error](http://i.imgur.com/epCOCY3.png)

**Comment by krzemin** [comment]
Thanks for reporting. I fixed it by forcing to kill any running `qnapi.exe` when nsis installer starts.

Change will be available once 0.2.2 installer is released.
