### ISSUE TITLE
Project ERROR: libmediainfo development package not found

### ISSUE THREAD

**Issue by kgarlicki** [QNapi/qnapi#58]
qmake complains about libmediainfo dev pkg but it's installed:
http://pastebin.com/raw/Q0ismUQR

**Comment by krzemin** [comment]
Do you have pkg-config installed?

**Comment by kgarlicki** [comment]
Package pkgconfig-1:0.28-9.fc23.x86_64 is already installed

**Comment by pulina** [comment]
I face same problem you need to install libmediainfo-devel

**Comment by kgarlicki** [comment]
Did you looked in the pastebin link?

**Comment by pulina** [comment]
Sorry i view your link and when i solve my problem, I write my answer not mind about your question. But i have some experience in debugging this. 

qmake use command  'pkg-config --exists libmediainfo' to check that libmediainfo.so exist. And pkg-config check his own folder with libinfo in (in my case) /usr/lib64/pkgconfig/. And if he not find libmediainfo.pc exit 1. So in my case libmediainfo.pc is supplayed by libmediainfo-devel:

```
rpm -ql libmediainfo-devel                                      
...
/usr/lib64/pkgconfig/libmediainfo.pc
...
```

Check that in your case bellowed code returns 0
```
[pulina ~/git/qnapi]% pkg-config --exists libmediainfo       
[pulina ~/git/qnapi]% echo $?                                
0
```
If not check that you have pkg-config installed and strace it to find out what  files it check. Mayby you have /usr/lib/pkgconfig/libmediainfo.pc file but it searching for /usr/lib64/pkgconfig/libmediainfo.pc.

**Comment by kgarlicki** [comment]
I've found out that this error was caused by enabed 3rd party repo which also had libmediainfo (not rpmfusion). This is resolved now. 

As a plus, I've got additional prerequisites for missing header files from OpenGL devel package, but in the coming days I will redo whole process on Fedora 24, so maybe than I will share steps for the procedure for Fedora users.

Thanks for the help!
