### ISSUE TITLE
fatal error: QtWidgets: no file or directory

### ISSUE THREAD

**Issue by egomi120** [QNapi/qnapi#59]
src/qcheckedlistwidget.h:18:21: fatal error: QtWidgets: Nie ma takiego pliku ani katalogu
http://pastebin.com/raw/Us4bkYzK

**Comment by krzemin** [comment]
Qt4? aktualna wersja korzysta z Qt5

**Comment by egomi120** [comment]
Faktycznie, moje przeoczenie. Zainstalowało się poprawnie z Qt5.
