### ISSUE TITLE
Instalacja

### ISSUE THREAD

**Issue by Kwiryniusz** [QNapi/qnapi#62]
Witam.
Wiem, ze mój problem moze wydać się śmieszny, ale...
Nie jestem zbyt zaawansowanym uzytkownikiem Linuksa. 
Nie umiem zainstalowac tego programu na Ubuntu i nigdzie nie potrafie znaleźć czytelnej instrukcji.
Prosze o pomoc.

**Comment by krzemin** [comment]
`sudo apt-get install qnapi` - to zainstaluje starsza wersje (bodajze 0.1.9 jest obecnie w repozytoriach)

Aby miec najnowszą, musisz kompilowac ze zródeł. Instrukcja jest tutaj: https://github.com/QNapi/qnapi/blob/master/README.md

**Comment by egomi120** [comment]
Kwiryniuszu żeby ci pomóc zrobiłem filmik jak można skompilować  https://www.youtube.com/watch?v=e7Zbo1JFVYE

**Comment by krzemin** [comment]
Dzięki!
