### ISSUE TITLE
Make packages for version 0.2.1 in Debian and Ubuntu

### ISSUE THREAD

**Issue by miniworm** [QNapi/qnapi#63]
Sadly latest package available in Debian and Ubuntu is still 0.1.9. Ubuntu now get prepares to release LTS release supported for 5 years so IMHO it would be good idea to ensure that latest version is available.

**Comment by maciex** [comment]
I think it's rather a question to Debian/Ubuntu developers.
I emailed Debian developers about this problem, but no response as of today.

[Debian Bug report logs - #807758 qnapi: New upstream version released (0.2.0)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807758)

**Comment by e-M-c-E** [comment]
Is not that hard to compile it ;)
Check this video: https://www.youtube.com/watch?v=e7Zbo1JFVYE
BTW.. Works great in Mint 18 Mate x64!

**Comment by krzemin** [comment]
Finally, packages for 0.2.2 are available for Xenial.

```
sudo add-apt-repository ppa:krzemin/qnapi
sudo apt-get update
sudo apt-get install qnapi
```

**Comment by pfk-beta** [comment]
@krzemin thanks for your great work! I've got message during adding your repository:
```
Err:5 http://ppa.launchpad.net/krzemin/qnapi/ubuntu focal Release                                                     
  404  Not Found [IP: 91.189.95.85 80]
Get:6 http://archive.ubuntu.com/ubuntu focal-proposed InRelease [267 kB]
Reading package lists... Done       
E: The repository 'http://ppa.launchpad.net/krzemin/qnapi/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
