### ISSUE TITLE
Zmień znaki diakrytyczne na ich odpowiedniki ASCII

### ISSUE THREAD

**Issue by maciak** [QNapi/qnapi#64]
Opcja zmienia wszystkie polskie znaczki za wyjatkiem ń.

**Comment by krzemin** [comment]
Poprawione, dzięki za info.

**Comment by maciak** [comment]
Widze ze poprawiles male ń ale duzego tez brakuje ;)

**Comment by krzemin** [comment]
Jest i duże.
