### ISSUE TITLE
Problem z kompilacją na CentOS

### ISSUE THREAD

**Issue by mieeeetek** [QNapi/qnapi#67]
Witam,
Mam problem przy kompilacji na CentOS 6.5.
Qt v. 5.6.0:

_compiling src/qnapiconfig.cpp
src/qnapiconfig.cpp: In member function ‘QStringList QNapiConfig::movieExtensions()’:
**src/qnapiconfig.cpp:699: error: no matching function for call to ‘QStringList::QStringList(<brace-enclosed initializer list>)’**
/usr/include/qt5/QtCore/qstringlist.h:101: note: candidates are: QStringList::QStringList(QList<QString>&&)
/usr/include/qt5/QtCore/qstringlist.h:99: note:                 QStringList::QStringList(const QList<QString>&)
/usr/include/qt5/QtCore/qstringlist.h:97: note:                 QStringList::QStringList()
/usr/include/qt5/QtCore/qstringlist.h:94: note:                 QStringList::QStringList(const QStringList&)
src/qnapiconfig.cpp: In member function ‘QStringList QNapiConfig::subtitleExtensions()’:
**src/qnapiconfig.cpp:718: error: no matching function for call to ‘QStringList::QStringList(<brace-enclosed initializer list>)’**
/usr/include/qt5/QtCore/qstringlist.h:101: note: candidates are: QStringList::QStringList(QList<QString>&&)
/usr/include/qt5/QtCore/qstringlist.h:99: note:                 QStringList::QStringList(const QList<QString>&)
/usr/include/qt5/QtCore/qstringlist.h:97: note:                 QStringList::QStringList()
/usr/include/qt5/QtCore/qstringlist.h:94: note:                 QStringList::QStringList(const QStringList&)
make: **\* [tmp/qnapiconfig.o] Error 1_

**Comment by krzemin** [comment]
Hej, najwyraźniej potrzebujesz nowszego kompilatora, który wspiera standard c++11.
