### ISSUE TITLE
komunikat o rezultacie w trybie cichym

### ISSUE THREAD

**Issue by LeonSolmyr** [QNapi/qnapi#69]
Hej,

Czy jest możliwość dodania opcji, aby w trybie cichym pojawiał się dymek (z traya) z komunikatem o rezultacie wyszukiwania?
np. "pobrano napisy języka głównego (PL)", "pobrano napisy języka zapasowego (ANG)", lub "nie znaleziono pasujących napisów"
Z jednej strony bardzo doceniam, że program ma tryb cichy i po wykonaniu pracy nie zostaje w trayu, ale z drugiej zdarza się, że nie mam pewności, czy proces wyszukiwania już się zakończył niepowodzeniem. Bardzo fajna byłaby możliwość aktywacji takiej "chmurki" z komunikatem, oraz wyboru, czy w chmurce ma się pokazywać każdy komunikat, czy tylko o niepowodzeniu.

**Comment by krzemin** [comment]
Hej, dzięki za propozycję, ale na razie jestem sceptyczny. Tryb cichy ma być właśnie bez żadnych komunikatów, a rezultat wykonania można odczytać przy użyciu kodu odpowiedzi zwracanego do systemu operacyjnego.

Twój przypadek dałoby się pewnie łatwo załatwić za pomocą 3-linijkowego skryptu, który przekazuje ścieżkę do pliku z filmem do qnapi w trybie cichym i w zależności od kodu odpowiedzi wyświetla odpowiedni dymek, np. przy użyciu http://www.paralint.com/projects/notifu/
