### ISSUE TITLE
Język zapasowy pobierany z prefixem ENG w nazwie pliku z napisami

### ISSUE THREAD

**Issue by LOLfan** [QNapi/qnapi#72]
Cześć, czy jest możliwość żeby napisy były pobierane od razu w dwóch językach (domyślnym i zapasowym)? + dla języka zapasowego ustawionego w opcjach byłyby pobierane z prefixem ENG dla np. języka angielskiego?

**Comment by uded** [comment]
Sugerowałbym krok dalej - niech ten prefix, np. `.{LANG}.[srt|txt]` będzie konfigurowalny także dla języka głównego. Mały ukłon w stronę użytkowników Plexa i podobnych systemów.
