### ISSUE TITLE
Problem ze ścieżką do qmake przy kompilacji

### ISSUE THREAD

**Issue by morgoth** [QNapi/qnapi#73]
Po ściągnięciu źródła 0.2.1:
```
wojtek@tp:~/Downloads/qnapi-0.2.1$ qmake 
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
wojtek@tp:~/Downloads/qnapi-0.2.1$ which qmake 
/usr/bin/qmake
wojtek@tp:~/Downloads/qnapi-0.2.1$ uname -a
Linux tp 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by morgoth** [comment]
Pomogło:
```
sudo apt-get install qt5-default libmediainfo-dev
```

**Comment by kepinskidar** [comment]
Ok, qmake działa, ale przy make jest problem
`dariusz@Lenovo-Z580 ~/Pulpit/qnapi-0.2.1 $ qmake
dariusz@Lenovo-Z580 ~/Pulpit/qnapi-0.2.1 $ make
compiling src/main.cpp
In file included from src/forms/frmprogress.h:20:0,
                 from src/qnapiapp.h:30,
                 from src/main.cpp:25:
tmp/ui_frmprogress.h:13:25: fatal error: QtGui/QAction: Nie ma takiego pliku ani katalogu
compilation terminated.
Makefile:931: polecenia dla obiektu 'tmp/main.o' nie powiodły się
make: *** [tmp/main.o] Błąd 1
dariusz@Lenovo-Z580 ~/Pulpit/qnapi-0.2.1 $`
