### ISSUE TITLE
Typ konwertowania plików

### ISSUE THREAD

**Issue by karczewp** [QNapi/qnapi#8]
Pryzdałaby się opcja konwertowania plikó do formatu ANSI.

**Comment by krzemin** [comment]
Technicznie rzecz biorąc - nie ma czegoś takiego jak "format ANSI".

http://stackoverflow.com/questions/701882/what-is-ansi-format

Przetwarzanie napisów do konkretnych kodowań można ustawić w opcjach.

**Comment by karczewp** [comment]
W praktyce jednak mam możliwość przekonwertowania plików do "formatu ANSI" w Notepadzie++. Efektem czego jest brak 'krzaków' zamiast polskich liter, natomiast na chwilę obecną pobierane napisy, bez względu na wybrany typ konwertowania, zawierają 'krzaki' zamiast polskich liter. Przekonwerotwania natomiast tychże napisów przy użyciu Notepada++ do "formatu ANSI" rozwiązuje problem i poprawnie koduje polskie znaki.

**Comment by krzemin** [comment]
Spróbuj konwersji do windows-1250.

**Comment by karczewp** [comment]
Niestety, dalej to samo.

**Comment by krzemin** [comment]
A auto-wykrywanie kodowania źródłowego masz włączone?

Alternatywnie można jeszcze usunąć polskie "ogonki" i zamienić je na odpowiedniki ASCII (np. ą -> a, ć -> c, ...). Rozwiązanie nie do końca idealne, ale przynajmniej da się rozczytać.

**Comment by karczewp** [comment]
Tak, włączone. 
Usunięcie ogonków robię właśnie poprzez przekonwertowanie pobranych plików w Notepadzie++ do "ANSI". Wtedy automatycznie mam polskie znaki poprawnie wyświetlane. Dodam, że odtwrzam w Bestplayerze.
