### ISSUE TITLE
Opcjonalne GUI

### ISSUE THREAD

**Issue by mmalisz** [QNapi/qnapi#81]
Czy Qt w QNapi odpowiada tylko za GUI, czy również za bazowe funkcjonalności?
Posiadam domowy headless server z rolą NAS'a, więc CLI jest jak najbardziej przydatne, jednak aby skompilować aplikację wymagane jest Qt.
Czy jest możliwość dodania opcji, w której kompilacja z użyciem Qt (qmake) jest opcjonalna?

**Comment by stil** [comment]
Qt to framework, który nie służy wyłącznie do tworzenia aplikacji okienkowych. QNapi używa Qt wszędzie, na przykład do połączeń sieciowych, operacji na systemie plików itd. Myśl o Qt jak o .NET Frameworku.

Odpowiadając na pytanie: nie jest możliwa kompilacja bez Qt.

**Comment by mmalisz** [comment]
Dzięki za odpowiedź. W takim razie zamykam.

**Comment by krzemin** [comment]
Jak słusznie zauważył @stil QtCore/QtNetwork/QtXml jest wymagane i tego raczej się nie pozbędziemy. Natomiast jest możliwe zrobienie osobnej binarki działającej tylko w trybie CLI, która nie byłaby zależna od QtWidgets (i wszystkich bibliotek X11). Pewne kroki ku temu zostały już podjęte.
