### ISSUE TITLE
Right-click menu entry not appearing under Windows 10

### ISSUE THREAD

**Issue by oczkers** [QNapi/qnapi#9]
Just like in napiprojekt

**Comment by krzemin** [comment]
You mean this?

http://qnapi.github.io/images/screenshots/0.1.7/win02.png

**Comment by oczkers** [comment]
Yeah, that's exactly what i mean. Am i so blind or did You add it manually?

**Comment by krzemin** [comment]
Under Windows/OSX it should be enabled by default. However I'm aware that integration isn't perfect and under some circumstances context menu entries could not appear (in that case please report a bug).

There are some problems in Linux, because there are so many file maganers and context-menu integration should be performed via specific distribution packages (like qnapi-gnome, qnapi-kde, etc.).

**Comment by oczkers** [comment]
I'm using win10 and looks like installator successfully add registry entries but somehow it's not working. Do You have any idea what could be the reason?

http://s2.postimg.org/4mk6co8mh/image.png

**Comment by krzemin** [comment]
Does it work for file extensions other than .mkv?

Could you also please paste values of registry entries under `napiprojekt/command` and `qnapi-pobierz/command` just for comparison?

**Comment by oczkers** [comment]
```
"C:\Program Files (x86)\NapiProjekt\napisy.exe" "%1"
"C:\Program Files (x86)\QNapi\qnapi.exe" "%1"
```

I've removed napiprojekt key and restarted explorer but nothing changes (napiprojekt entry still avaible in right-click menu) so it has to be located somewhere else

**Comment by spoksik** [comment]
http://www.wykop.pl/link/2673211/#comment-29866373

**Comment by krzemin** [comment]
@oczkers: could you confirm that above solution work for you?

**Comment by spoksik** [comment]
@krzemin my solution works ;]

**Comment by oczkers** [comment]
Yes, it's not beautiful and works ;-)
http://s16.postimg.org/r2rwxz7gl/image.png

**Comment by spoksik** [comment]
text is original from qnapi, u can set whateever u like in *.reg file  :)

**Comment by krzemin** [comment]
Ok, so I will modify Windows installer according to @spoksik's solution.

Any suggestions how to make it "more beautiful"? :)

**Comment by oczkers** [comment]
qnapi-pobierz or simple "qnapi" just looks clean and ordered for me :-)

http://s23.postimg.org/agvwbho1n/image.png
