### ISSUE TITLE
Ubuntu - bardzo ograniczony dostęp do plików

### ISSUE THREAD

**Issue by Avaray** [QNapi/qnapi#92]
`Qnapi > pobierz  napisy`
W okienku wyboru plików widać jedynie "mój komputer" i katalog użytkownika wraz z podkatalogami.
Nie mam dostępu do żadnej innej lokalizacji (innych partycji, dysków twardych, przenośnych itp.).
Nie wiem czy to przez brak jakichś uprawnień dla tej aplikacji.

Instalowałem poprzez apt-get; działam na Ubuntu 16.04.

**Comment by krzemin** [comment]
zrzut ekranu?

**Comment by Avaray** [comment]
Jednak jest to wina moja lub systemu.
Sprawdziłem w innych programach (Steam, VLC Player, Krita, Dropbox) i w nich mam tak samo.
Natomiast nie mam tego problemu w przeglądarkach internetowych i programach tj. Atom, VSCode, MonoDevelop, VirtualBox, Liferea, Transmission, DeaDBeef.

Wygląda to tak: 
![](http://i.imgur.com/E4FmYvg.png)

**Comment by krzemin** [comment]
Hmm, to okienko nie ogranicza dostępu do plików. Inne dyski czy partycje są najprawdopodobniej w `/mnt` lub `/media`, do których można przejść klikając w `/`.

Inna sprawa, że pod Linuksem Qt nie zawsze potrafi wyświetlić natywne okno wyboru plików. W każdym razie nie sądzę, że można tu cokolwiek zrobić po stronie QNapi.
