### ISSUE TITLE
Problem z pakietem PPA na Ubuntu Linux 14.04 LTE

### ISSUE THREAD

**Issue by BartoszBartniczak** [QNapi/qnapi#95]
Witaj. 
Nie mogę pobrać listy pakietów przy poleceniu apt-get update.

W: Nie udało się pobrać http://ppa.launchpad.net/krzemin/qnapi/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 172.217.22.110 80]

**Comment by krzemin** [comment]
Hej. Niestety, pakiety w tym repo są przygotowane na razie tylko dla Xenial i Yakkety.

**Comment by BartoszBartniczak** [comment]
Szkoda. Po małej walce z QT udało mi się skompilować źródło. Czy na Linuxie dostępna jest tylko wersja konsolowa? Po odpaleniu `./qnapi` nie dzieje się nic.

**Comment by krzemin** [comment]
Z tego, co pamiętam, to na starszych wersjach Ubuntu był problem z obsługą ikony w tray-u. W Unity od pewnego czasu nie ma systemowego tray'a, tylko własne rozwiązanie na bazie **libindicator**. Qt potrafi to wspierać, ale dopiero od wersji 5.5. Domyślna wersja w Trusty jest chyba jakaś starsza, więc żeby wszystko zadziałało jak należy, trzeba zainstalować sobie nowsze Qt (przynajmniej 5.5) i skompilować QNapi przy jego użyciu.

Jest to trochę pokręcone i właśnie dlatego nie wypuszczam paczek dla Trusty.
